### ISSUE TITLE
Minor design considerations

### ISSUE THREAD

**Issue by vityok** [pnathan/articulate-common-lisp#28]
The site looks nice, but I guess it would be even better if the navigation items in the top menu had friendlier labels (instead of ids, page titles).

For example, instead of "env" write "Development environment", instead of "new-project" write "Creating a new project in Common Lisp" etc.

Also I guess it would be nice if the text body was a little bit not so wide, this could make reading easier.

**Comment by pnathan** [comment]
Navbar issues including names should be resolved in #33 . @vityok - if you still care about this, please reopen.
