### ISSUE TITLE
Implementations aren't "systems"

### ISSUE THREAD

**Issue by fare** [pnathan/articulate-common-lisp#37]
«Common Lisp implementations usually are called “systems”» says env/lisp-systems.html

That's the first time I hear of implementations called "systems". They are usually "implementations", or when the OS (and optionally CPU) is also specified, "platform". I would remove that remark and rename the page.

A link from implementation to implementation-specific page in that page would be nice.

**Comment by fare** [comment]
I would also call SBCL "highest speed compiler". Then again, the compiler itself is the slowest. It's the code it produces that's fast.

So, for SBCL, I'd write "compiles to fastest code; good on Linux, OSX but less so on Windows".

For CCL, I'd write "compiles fast to fast code; good on Linux, OSX, Windows; commercial support".

Or I'd make a grid for how well each OS is supported.

**Comment by pnathan** [comment]
H'm. I don't know where I derived that idea that implementation==system. It's not supported by CLTL2 in any case. I shall fix it.

Also, thanks for the heads up on the wordsmithing needed for SBCL.
